# Generated by Django 4.0.6 on 2022-08-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver',
            name='status',
            field=models.CharField(choices=[('inway', 'در راه'), ('pickup', 'در حال دریافت از رستوران'), ('deliverd', 'تحویل داده شده'), ('ndeliverd', 'تحویل داده نشده'), ('wating_for_ready', 'در انتظار آماده سازی')], max_length=20),
        ),
    ]
