# Generated by Django 4.0.3 on 2022-07-13 12:02

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant.models.restaurant_directory_path)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=12)),
                ('deliver_fee', models.IntegerField(blank=True, null=True)),
                ('is_delivery_available', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('open_hour', models.TimeField(blank=True, null=True)),
                ('close_hour', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
