# Generated by Django 4.0.6 on 2022-07-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='deliver_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
