# Generated by Django 4.0.6 on 2022-08-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_temp_order'),
        ('restaurant', '0005_alter_restaurant_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tax_delivery',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tax_fix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tax_food',
            field=models.SmallIntegerField(default=0),
        ),
    ]
