# Generated by Django 4.0.6 on 2022-08-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderdate_disable'),
        ('user', '0003_profile_temp_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='temp_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_user', to='order.order'),
        ),
    ]
