# Generated by Django 4.0.3 on 2022-07-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateFoodCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('foods', models.ManyToManyField(blank=True, to='order.datefoodcount')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_type', models.CharField(blank=True, choices=[('takeout', 'تحویل حضوری'), ('deliver', 'ارسال درب منزل')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('temp', 'موقت'), ('pending_confirm', 'در انتظار تایید'), ('confirmed', 'سفارش پذیرفته شده'), ('in_progress', 'در حال آماده سازی'), ('delivery', 'تحویل به پیک'), ('delivered', 'تحویل به مشتری'), ('failed', 'پذیرفته نشده'), ('wating_for_pay', 'منتظر پرداخت'), ('not_confirmed', 'تایید نشده')], default='temp', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('target_date', models.DateField()),
                ('foods', models.ManyToManyField(blank=True, to='order.foodcount')),
                ('order_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderdate')),
            ],
        ),
    ]
