# Generated by Django 4.0.6 on 2022-07-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='آدرس گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(blank=True, to='order.foodcount', verbose_name='غذاها'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderdate', verbose_name='تاریخ مرجع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('temp', 'موقت'), ('pending_confirm', 'در انتظار تایید'), ('confirmed', 'سفارش پذیرفته شده'), ('in_progress', 'در حال آماده سازی'), ('delivery', 'تحویل به پیک'), ('delivered', 'تحویل به مشتری'), ('failed', 'پذیرفته نشده'), ('wating_for_pay', 'منتظر پرداخت'), ('not_confirmed', 'تایید نشده')], default='temp', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='target_date',
            field=models.DateField(verbose_name='تاریخ تحویل سفارش'),
        ),
    ]
