# Generated by Django 4.0.3 on 2022-07-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
        ('order', '0005_alter_order_address_alter_order_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdate',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.restaurant', verbose_name='رستوران  '),
        ),
    ]
