# Generated by Django 4.0.3 on 2022-08-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderdate_restaurant_alter_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('temp', 'موقت'), ('pending_confirm', 'در انتظار تایید'), ('confirmed', 'سفارش پذیرفته شده'), ('in_progress', 'در حال آماده سازی'), ('delivery', 'تحویل به پیک'), ('delivered', 'تحویل به مشتری'), ('failed', 'پذیرفته نشده'), ('not_confirmed', 'تایید نشده')], default='temp', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderdate',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='order_date', to='order.datefoodcount'),
        ),
    ]
