# Generated by Django 4.0.6 on 2022-08-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_deliver_fee'),
        ('food', '0002_initial'),
        ('order', '0007_alter_order_status_alter_orderdate_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('temp', 'موقت'), ('pending_confirm', 'در انتظار تایید'), ('confirmed', 'سفارش پذیرفته شده'), ('in_progress', 'در حال آماده سازی'), ('delivery', 'تحویل به پیک'), ('delivered', 'تحویل داده شده به مشتری'), ('failed', 'به مشکل برخورده'), ('not_confirmed', 'تایید نشده')], default='temp', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderdate',
            name='date',
            field=models.DateField(unique=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='orderdate',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='order_date', to='order.datefoodcount', verbose_name='غذاها'),
        ),
        migrations.AlterField(
            model_name='orderdate',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='رستوران مربوطه'),
        ),
        migrations.CreateModel(
            name='FixMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام منو')),
                ('foods', models.ManyToManyField(to='food.food', verbose_name='غذا ها')),
            ],
        ),
        migrations.AddField(
            model_name='orderdate',
            name='fix_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.fixmenu', verbose_name='منوی ثابت'),
        ),
    ]
