# Generated by Django 4.0.6 on 2022-08-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_status_alter_orderdate_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixmenu',
            options={'verbose_name': 'منوی ثابت', 'verbose_name_plural': 'منو های ثابت'},
        ),
        migrations.AlterModelOptions(
            name='orderdate',
            options={'verbose_name': 'منوی تاریخ دار', 'verbose_name_plural': 'منو های تاریخ دار'},
        ),
        migrations.AlterField(
            model_name='fixmenu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام منو'),
        ),
    ]
