# Generated by Django 4.0.6 on 2022-08-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_max_reserve_time_restaurant_tax_delivery_and_more'),
        ('order', '0009_alter_fixmenu_options_alter_orderdate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixmenu',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='رستوران'),
            preserve_default=False,
        ),
    ]
