# Generated by Django 4.0.6 on 2022-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderdate_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meal_type',
            field=models.CharField(choices=[('dinner', 'ناهار'), ('lunch', 'ناهار')], default='lunch', max_length=20, verbose_name='نوع سفارش'),
        ),
    ]
